/*!
 * Knockout JavaScript library v3.3.0
 * (c) Steven Sanderson - http://knockoutjs.com/
 * License: MIT (http://www.opensource.org/licenses/mit-license.php)
 */

(function() {(function(p){var y=this||(0,eval)("this"),u=y.document,N=y.navigator,v=y.jQuery,D=y.JSON;(function(p){"function"===typeof define&&define.amd?define(["exports","require"],p):"function"===typeof require&&"object"===typeof exports&&"object"===typeof module?p(module.exports||exports):p(y.ko={})})(function(O,P){function J(a,d){return null===a||typeof a in R?a===d:!1}function S(b,d){var c;return function(){c||(c=a.a.setTimeout(function(){c=p;b()},d))}}function T(b,d){var c;return function(){clearTimeout(c);
c=a.a.setTimeout(b,d)}}function U(a,d){d&&d!==H?"beforeChange"===d?this.rb(a):this.va(a,d):this.sb(a)}function K(b,d,c,e){a.d[b]={init:function(b,h,k,l,f){var m,x;a.w(function(){var q=a.a.c(h()),n=!c!==!q,l=!x;if(l||d||n!==m)l&&a.$.qa()&&(x=a.a.ma(a.e.childNodes(b),!0)),n?(l||a.e.U(b,a.a.ma(x)),a.Na(e?e(f,q):f,b)):a.e.na(b),m=n},null,{q:b});return{controlsDescendantBindings:!0}}};a.h.la[b]=!1;a.e.S[b]=!0}var a="undefined"!==typeof O?O:{};a.b=function(b,d){for(var c=b.split("."),e=a,g=0;g<c.length-
1;g++)e=e[c[g]];e[c[c.length-1]]=d};a.D=function(a,d,c){a[d]=c};a.version="3.3.0";a.b("version",a.version);a.options={deferUpdates:!1};a.a=function(){function b(a,b){for(var c in a)a.hasOwnProperty(c)&&b(c,a[c])}function d(a,b){if(b)for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c]);return a}function c(a,b){a.__proto__=b;return a}function e(b,c,f,d){var e=b[c].match(m)||[];a.a.o(f.match(m),function(b){a.a.ha(e,b,d)});b[c]=e.join(" ")}var g={__proto__:[]}instanceof Array,h={},k={};h[N&&/Firefox\/2/i.test(N.userAgent)?
"KeyboardEvent":"UIEvents"]=["keyup","keydown","keypress"];h.MouseEvents="click dblclick mousedown mouseup mousemove mouseover mouseout mouseenter mouseleave".split(" ");b(h,function(a,b){if(b.length)for(var c=0,f=b.length;c<f;c++)k[b[c]]=a});var l={propertychange:!0},f=u&&function(){for(var a=3,b=u.createElement("div"),c=b.getElementsByTagName("i");b.innerHTML="\x3c!--[if gt IE "+ ++a+"]><i></i><![endif]--\x3e",c[0];);return 4<a?a:p}(),m=/\S+/g;return{Fb:["authenticity_token",/^__RequestVerificationToken(_.*)?$/],
o:function(a,b){for(var c=0,f=a.length;c<f;c++)b(a[c],c)},m:function(a,b){if("function"==typeof Array.prototype.indexOf)return Array.prototype.indexOf.call(a,b);for(var c=0,f=a.length;c<f;c++)if(a[c]===b)return c;return-1},xb:function(a,b,c){for(var f=0,d=a.length;f<d;f++)if(b.call(c,a[f],f))return a[f];return null},Aa:function(b,c){var f=a.a.m(b,c);0<f?b.splice(f,1):0===f&&b.shift()},yb:function(b){b=b||[];for(var c=[],f=0,d=b.length;f<d;f++)0>a.a.m(c,b[f])&&c.push(b[f]);return c},Oa:function(a,
b){a=a||[];for(var c=[],f=0,d=a.length;f<d;f++)c.push(b(a[f],f));return c},za:function(a,b){a=a||[];for(var c=[],f=0,d=a.length;f<d;f++)b(a[f],f)&&c.push(a[f]);return c},ja:function(a,b){if(b instanceof Array)a.push.apply(a,b);else for(var c=0,f=b.length;c<f;c++)a.push(b[c]);return a},ha:function(b,c,f){var d=a.a.m(a.a.fb(b),c);0>d?f&&b.push(c):f||b.splice(d,1)},Ba:g,extend:d,Ja:c,Ka:g?c:d,A:b,ra:function(a,b){if(!a)return a;var c={},f;for(f in a)a.hasOwnProperty(f)&&(c[f]=b(a[f],f,a));return c},
Va:function(b){for(;b.firstChild;)a.removeNode(b.firstChild)},Nb:function(b){b=a.a.O(b);for(var c=(b[0]&&b[0].ownerDocument||u).createElement("div"),f=0,d=b.length;f<d;f++)c.appendChild(a.T(b[f]));return c},ma:function(b,c){for(var f=0,d=b.length,e=[];f<d;f++){var m=b[f].cloneNode(!0);e.push(c?a.T(m):m)}return e},U:function(b,c){a.a.Va(b);if(c)for(var f=0,d=c.length;f<d;f++)b.appendChild(c[f])},Ub:function(b,c){var f=b.nodeType?[b]:b;if(0<f.length){for(var d=f[0],e=d.parentNode,m=0,l=c.length;m<l;m++)e.insertBefore(c[m],
d);m=0;for(l=f.length;m<l;m++)a.removeNode(f[m])}},pa:function(a,b){if(a.length){for(b=8===b.nodeType&&b.parentNode||b;a.length&&a[0].parentNode!==b;)a.splice(0,1);if(1<a.length){var c=a[0],f=a[a.length-1];for(a.length=0;c!==f;)if(a.push(c),c=c.nextSibling,!c)return;a.push(f)}}return a},Wb:function(a,b){7>f?a.setAttribute("selected",b):a.selected=b},kb:function(a){return null===a||a===p?"":a.trim?a.trim():a.toString().replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")},Jc:function(a,b){a=a||"";return b.length>
a.length?!1:a.substring(0,b.length)===b},oc:function(a,b){if(a===b)return!0;if(11===a.nodeType)return!1;if(b.contains)return b.contains(3===a.nodeType?a.parentNode:a);if(b.compareDocumentPosition)return 16==(b.compareDocumentPosition(a)&16);for(;a&&a!=b;)a=a.parentNode;return!!a},Ua:function(b){return a.a.oc(b,b.ownerDocument.documentElement)},vb:function(b){return!!a.a.xb(b,a.a.Ua)},v:function(a){return a&&a.tagName&&a.tagName.toLowerCase()},Bb:function(b){return a.onError?function(){try{return b.apply(this,
arguments)}catch(c){throw a.onError&&a.onError(c),c;}}:b},setTimeout:function(b,c){return setTimeout(a.a.Bb(b),c)},Eb:function(b){setTimeout(function(){a.onError&&a.onError(b);throw b;},0)},n:function(b,c,d){var e=a.a.Bb(d);d=f&&l[c];if(!d&&v)v(b).bind(c,e);else if(d||"function"!=typeof b.addEventListener)if("undefined"!=typeof b.attachEvent){var m=function(a){e.call(b,a)},g="on"+c;b.attachEvent(g,m);a.a.C.ga(b,function(){b.detachEvent(g,m)})}else throw Error("Browser doesn't support addEventListener or attachEvent");
else b.addEventListener(c,e,!1)},sa:function(b,c){if(!b||!b.nodeType)throw Error("element must be a DOM node when calling triggerEvent");var f;"input"===a.a.v(b)&&b.type&&"click"==c.toLowerCase()?(f=b.type,f="checkbox"==f||"radio"==f):f=!1;if(v&&!f)v(b).trigger(c);else if("function"==typeof u.createEvent)if("function"==typeof b.dispatchEvent)f=u.createEvent(k[c]||"HTMLEvents"),f.initEvent(c,!0,!0,y,0,0,0,0,0,!1,!1,!1,!1,0,b),b.dispatchEvent(f);else throw Error("The supplied element doesn't support dispatchEvent");
else if(f&&b.click)b.click();else if("undefined"!=typeof b.fireEvent)b.fireEvent("on"+c);else throw Error("Browser doesn't support triggering events");},c:function(b){return a.F(b)?b():b},fb:function(b){return a.F(b)?b.B():b},Ma:function(b,c,f){var d;c&&("object"===typeof b.classList?(d=b.classList[f?"add":"remove"],a.a.o(c.match(m),function(a){d.call(b.classList,a)})):"string"===typeof b.className.baseVal?e(b.className,"baseVal",c,f):e(b,"className",c,f))},La:function(b,c){var f=a.a.c(c);if(null===
f||f===p)f="";var d=a.e.firstChild(b);!d||3!=d.nodeType||a.e.nextSibling(d)?a.e.U(b,[b.ownerDocument.createTextNode(f)]):d.data=f;a.a.rc(b)},Vb:function(a,b){a.name=b;if(7>=f)try{a.mergeAttributes(u.createElement("<input name='"+a.name+"'/>"),!1)}catch(c){}},rc:function(a){9<=f&&(a=1==a.nodeType?a:a.parentNode,a.style&&(a.style.zoom=a.style.zoom))},pc:function(a){if(f){var b=a.style.width;a.style.width=0;a.style.width=b}},Gc:function(b,c){b=a.a.c(b);c=a.a.c(c);for(var f=[],d=b;d<=c;d++)f.push(d);
return f},O:function(a){for(var b=[],c=0,f=a.length;c<f;c++)b.push(a[c]);return b},Nc:6===f,Oc:7===f,M:f,Hb:function(b,c){for(var f=a.a.O(b.getElementsByTagName("input")).concat(a.a.O(b.getElementsByTagName("textarea"))),d="string"==typeof c?function(a){return a.name===c}:function(a){return c.test(a.name)},e=[],m=f.length-1;0<=m;m--)d(f[m])&&e.push(f[m]);return e},Dc:function(b){return"string"==typeof b&&(b=a.a.kb(b))?D&&D.parse?D.parse(b):(new Function("return "+b))():null},lb:function(b,c,f){if(!D||
!D.stringify)throw Error("Cannot find JSON.stringify(). Some browsers (e.g., IE < 8) don't support it natively, but you can overcome this by adding a script reference to json2.js, downloadable from http://www.json.org/json2.js");return D.stringify(a.a.c(b),c,f)},Ec:function(c,f,d){d=d||{};var e=d.params||{},m=d.includeFields||this.Fb,l=c;if("object"==typeof c&&"form"===a.a.v(c))for(var l=c.action,g=m.length-1;0<=g;g--)for(var h=a.a.Hb(c,m[g]),k=h.length-1;0<=k;k--)e[h[k].name]=h[k].value;f=a.a.c(f);
var r=u.createElement("form");r.style.display="none";r.action=l;r.method="post";for(var p in f)c=u.createElement("input"),c.type="hidden",c.name=p,c.value=a.a.lb(a.a.c(f[p])),r.appendChild(c);b(e,function(a,b){var c=u.createElement("input");c.type="hidden";c.name=a;c.value=b;r.appendChild(c)});u.body.appendChild(r);d.submitter?d.submitter(r):r.submit();setTimeout(function(){r.parentNode.removeChild(r)},0)}}}();a.b("utils",a.a);a.b("utils.arrayForEach",a.a.o);a.b("utils.arrayFirst",a.a.xb);a.b("utils.arrayFilter",
a.a.za);a.b("utils.arrayGetDistinctValues",a.a.yb);a.b("utils.arrayIndexOf",a.a.m);a.b("utils.arrayMap",a.a.Oa);a.b("utils.arrayPushAll",a.a.ja);a.b("utils.arrayRemoveItem",a.a.Aa);a.b("utils.extend",a.a.extend);a.b("utils.fieldsIncludedWithJsonPost",a.a.Fb);a.b("utils.getFormFields",a.a.Hb);a.b("utils.peekObservable",a.a.fb);a.b("utils.postJson",a.a.Ec);a.b("utils.parseJson",a.a.Dc);a.b("utils.registerEventHandler",a.a.n);a.b("utils.stringifyJson",a.a.lb);a.b("utils.range",a.a.Gc);a.b("utils.toggleDomNodeCssClass",
a.a.Ma);a.b("utils.triggerEvent",a.a.sa);a.b("utils.unwrapObservable",a.a.c);a.b("utils.objectForEach",a.a.A);a.b("utils.addOrRemoveItem",a.a.ha);a.b("utils.setTextContent",a.a.La);a.b("unwrap",a.a.c);Function.prototype.bind||(Function.prototype.bind=function(a){var d=this;if(1===arguments.length)return function(){return d.apply(a,arguments)};var c=Array.prototype.slice.call(arguments,1);return function(){var e=c.slice(0);e.push.apply(e,arguments);return d.apply(a,e)}});a.a.f=new function(){function a(b,
h){var k=b[c];if(!k||"null"===k||!e[k]){if(!h)return p;k=b[c]="ko"+d++;e[k]={}}return e[k]}var d=0,c="__ko__"+(new Date).getTime(),e={};return{get:function(c,d){var e=a(c,!1);return e===p?p:e[d]},set:function(c,d,e){if(e!==p||a(c,!1)!==p)a(c,!0)[d]=e},clear:function(a){var b=a[c];return b?(delete e[b],a[c]=null,!0):!1},I:function(){return d++ +c}}};a.b("utils.domData",a.a.f);a.b("utils.domData.clear",a.a.f.clear);a.a.C=new function(){function b(b,d){var e=a.a.f.get(b,c);e===p&&d&&(e=[],a.a.f.set(b,
c,e));return e}function d(c){var e=b(c,!1);if(e)for(var e=e.slice(0),l=0;l<e.length;l++)e[l](c);a.a.f.clear(c);a.a.C.cleanExternalData(c);if(g[c.nodeType])for(e=c.firstChild;c=e;)e=c.nextSibling,8===c.nodeType&&d(c)}var c=a.a.f.I(),e={1:!0,8:!0,9:!0},g={1:!0,9:!0};return{ga:function(a,c){if("function"!=typeof c)throw Error("Callback must be a function");b(a,!0).push(c)},Tb:function(d,e){var l=b(d,!1);l&&(a.a.Aa(l,e),0==l.length&&a.a.f.set(d,c,p))},T:function(b){if(e[b.nodeType]&&(d(b),g[b.nodeType])){var c=
[];a.a.ja(c,b.getElementsByTagName("*"));for(var l=0,f=c.length;l<f;l++)d(c[l])}return b},removeNode:function(b){a.T(b);b.parentNode&&b.parentNode.removeChild(b)},cleanExternalData:function(a){v&&"function"==typeof v.cleanData&&v.cleanData([a])}}};a.T=a.a.C.T;a.removeNode=a.a.C.removeNode;a.b("cleanNode",a.T);a.b("removeNode",a.removeNode);a.b("utils.domNodeDisposal",a.a.C);a.b("utils.domNodeDisposal.addDisposeCallback",a.a.C.ga);a.b("utils.domNodeDisposal.removeDisposeCallback",a.a.C.Tb);(function(){a.a.da=
function(b,d){var c;if(v)if(v.parseHTML)c=v.parseHTML(b,d)||[];else{if((c=v.clean([b],d))&&c[0]){for(var e=c[0];e.parentNode&&11!==e.parentNode.nodeType;)e=e.parentNode;e.parentNode&&e.parentNode.removeChild(e)}}else{(e=d)||(e=u);c=e.parentWindow||e.defaultView||y;var g=a.a.kb(b).toLowerCase(),e=e.createElement("div"),g=g.match(/^<(thead|tbody|tfoot)/)&&[1,"<table>","</table>"]||!g.indexOf("<tr")&&[2,"<table><tbody>","</tbody></table>"]||(!g.indexOf("<td")||!g.indexOf("<th"))&&[3,"<table><tbody><tr>",
"</tr></tbody></table>"]||[0,"",""],h="ignored<div>"+g[1]+b+g[2]+"</div>";for("function"==typeof c.innerShiv?e.appendChild(c.innerShiv(h)):e.innerHTML=h;g[0]--;)e=e.lastChild;c=a.a.O(e.lastChild.childNodes)}return c};a.a.ib=function(b,d){a.a.Va(b);d=a.a.c(d);if(null!==d&&d!==p)if("string"!=typeof d&&(d=d.toString()),v)v(b).html(d);else for(var c=a.a.da(d,b.ownerDocument),e=0;e<c.length;e++)b.appendChild(c[e])}})();a.b("utils.parseHtmlFragment",a.a.da);a.b("utils.setHtml",a.a.ib);a.H=function(){function b(c,
d){if(c)if(8==c.nodeType){var g=a.H.Pb(c.nodeValue);null!=g&&d.push({nc:c,Bc:g})}else if(1==c.nodeType)for(var g=0,h=c.childNodes,k=h.length;g<k;g++)b(h[g],d)}var d={};return{bb:function(a){if("function"!=typeof a)throw Error("You can only pass a function to ko.memoization.memoize()");var b=(4294967296*(1+Math.random())|0).toString(16).substring(1)+(4294967296*(1+Math.random())|0).toString(16).substring(1);d[b]=a;return"\x3c!--[ko_memo:"+b+"]--\x3e"},$b:function(a,b){var g=d[a];if(g===p)throw Error("Couldn't find any memo with ID "+
a+". Perhaps it's already been unmemoized.");try{return g.apply(null,b||[]),!0}finally{delete d[a]}},ac:function(c,d){var g=[];b(c,g);for(var h=0,k=g.length;h<k;h++){var l=g[h].nc,f=[l];d&&a.a.ja(f,d);a.H.$b(g[h].Bc,f);l.nodeValue="";l.parentNode&&l.parentNode.removeChild(l)}},Pb:function(a){return(a=a.match(/^\[ko_memo\:(.*?)\]$/))?a[1]:null}}}();a.b("memoization",a.H);a.b("memoization.memoize",a.H.bb);a.b("memoization.unmemoize",a.H.$b);a.b("memoization.parseMemoText",a.H.Pb);a.b("memoization.unmemoizeDomNodeAndDescendants",
a.H.ac);a.R=function(){function b(){if(e)for(var b=e,d=0,f;h<e;)if(f=c[h++]){if(h>b){if(5E3<=++d){h=e;a.a.Eb(Error("'Too much recursion' after processing "+d+" task groups."));break}b=e}try{f()}catch(m){a.a.Eb(m)}}}function d(){b();h=e=c.length=0}var c=[],e=0,g=1,h=0;return{scheduler:y.MutationObserver?function(a){var b=u.createElement("div");(new MutationObserver(a)).observe(b,{attributes:!0});return function(){b.classList.toggle("foo")}}(d):u&&"onreadystatechange"in u.createElement("script")?function(a){var b=
u.createElement("script");b.onreadystatechange=function(){b.onreadystatechange=null;u.documentElement.removeChild(b);b=null;a()};u.documentElement.appendChild(b)}:function(a){setTimeout(a,0)},Ia:function(b){e||a.R.scheduler(d);c[e++]=b;return g++},cancel:function(a){a-=g-e;a>=h&&a<e&&(c[a]=null)},resetForTesting:function(){var a=e-h;h=e=c.length=0;return a},Ic:b}}();a.b("tasks",a.R);a.b("tasks.schedule",a.R.Ia);a.b("tasks.runEarly",a.R.Ic);a.oa={throttle:function(b,d){b.throttleEvaluation=d;var c=
null;return a.j({read:b,write:function(e){clearTimeout(c);c=a.a.setTimeout(function(){b(e)},d)}})},rateLimit:function(a,d){var c,e,g;"number"==typeof d?c=d:(c=d.timeout,e=d.method);g="notifyWhenChangesStop"==e?T:S;a.Ga(function(a){return g(a,c)})},deferred:function(b,d){(b.ec=d)&&b.Ga(function(c){var d;return function(){a.R.cancel(d);b.ec?d=a.R.Ia(c):(d=0,c())}})},notify:function(a,d){a.equalityComparer="always"==d?null:J}};var R={undefined:1,"boolean":1,number:1,string:1};a.b("extenders",a.oa);a.Yb=
function(b,d,c){this.ea=b;this.Pa=d;this.mc=c;this.Kb=!1;a.D(this,"dispose",this.p)};a.Yb.prototype.p=function(){this.Kb=!0;this.mc()};a.Q=function(){a.a.Ka(this,a.Q.fn);this.G={};this.tb=1};var H="change",z={V:function(b,d,c){var e=this;c=c||H;var g=new a.Yb(e,d?b.bind(d):b,function(){a.a.Aa(e.G[c],g);e.wa&&e.wa(c)});e.ka&&e.ka(c);e.G[c]||(e.G[c]=[]);e.G[c].push(g);return g},notifySubscribers:function(b,d){d=d||H;d===H&&this.bc();if(this.Da(d))try{a.k.zb();for(var c=this.G[d].slice(0),e=0,g;g=c[e];++e)g.Kb||
g.Pa(b)}finally{a.k.end()}},Ca:function(){return this.tb},uc:function(a){return this.Ca()!==a},bc:function(){++this.tb},Ga:function(b){var d=this,c=a.F(d),e,g,h;d.va||(d.va=d.notifySubscribers,d.notifySubscribers=U);var k=b(function(){c&&h===d&&(h=d());e=!1;d.Za(g,h)&&d.va(g=h)});d.sb=function(a){e=!0;h=a;k()};d.rb=function(a){e||(g=a,d.va(a,"beforeChange"))}},Da:function(a){return this.G[a]&&this.G[a].length},sc:function(b){if(b)return this.G[b]&&this.G[b].length||0;var d=0;a.a.A(this.G,function(a,
b){d+=b.length});return d},Za:function(a,d){return!this.equalityComparer||!this.equalityComparer(a,d)},extend:function(b){var d=this;b&&a.a.A(b,function(b,e){var g=a.oa[b];"function"==typeof g&&(d=g(d,e)||d)});return d}};a.D(z,"subscribe",z.V);a.D(z,"extend",z.extend);a.D(z,"getSubscriptionsCount",z.sc);a.a.Ba&&a.a.Ja(z,Function.prototype);a.Q.fn=z;a.Lb=function(a){return null!=a&&"function"==typeof a.V&&"function"==typeof a.notifySubscribers};a.b("subscribable",a.Q);a.b("isSubscribable",a.Lb);a.$=
a.k=function(){function b(a){c.push(e);e=a}function d(){e=c.pop()}var c=[],e,g=0;return{zb:b,end:d,Sb:function(b){if(e){if(!a.Lb(b))throw Error("Only subscribable things can act as dependencies");e.Pa(b,b.fc||(b.fc=++g))}},u:function(a,c,e){try{return b(),a.apply(c,e||[])}finally{d()}},qa:function(){if(e)return e.w.qa()},Ea:function(){if(e)return e.Ea}}}();a.b("computedContext",a.$);a.b("computedContext.getDependenciesCount",a.$.qa);a.b("computedContext.isInitial",a.$.Ea);a.b("computedContext.isSleeping",
a.$.Pc);a.b("ignoreDependencies",a.Mc=a.k.u);a.r=function(b){function d(){if(0<arguments.length)return d.Za(c,arguments[0])&&(d.Y(),c=arguments[0],d.X()),this;a.k.Sb(d);return c}var c=b;a.Q.call(d);a.a.Ka(d,a.r.fn);d.B=function(){return c};d.X=function(){d.notifySubscribers(c)};d.Y=function(){d.notifySubscribers(c,"beforeChange")};a.D(d,"peek",d.B);a.D(d,"valueHasMutated",d.X);a.D(d,"valueWillMutate",d.Y);a.options.deferUpdates&&a.oa.deferred(d,!0);return d};a.r.fn={equalityComparer:J};var G=a.r.Fc=
"__ko_proto__";a.r.fn[G]=a.r;a.a.Ba&&a.a.Ja(a.r.fn,a.Q.fn);a.Wa=function(b,d){return null===b||b===p||b[G]===p?!1:b[G]===d?!0:a.Wa(b[G],d)};a.F=function(b){return a.Wa(b,a.r)};a.Fa=function(b){return"function"==typeof b&&b[G]===a.r||"function"==typeof b&&b[G]===a.j&&b.vc?!0:!1};a.b("observable",a.r);a.b("isObservable",a.F);a.b("isWriteableObservable",a.Fa);a.b("isWritableObservable",a.Fa);a.ca=function(b){b=b||[];if("object"!=typeof b||!("length"in b))throw Error("The argument passed when initializing an observable array must be an array, or null, or undefined.");
b=a.r(b);a.a.Ka(b,a.ca.fn);return b.extend({trackArrayChanges:!0})};a.ca.fn={remove:function(b){for(var d=this.B(),c=[],e="function"!=typeof b||a.F(b)?function(a){return a===b}:b,g=0;g<d.length;g++){var h=d[g];e(h)&&(0===c.length&&this.Y(),c.push(h),d.splice(g,1),g--)}c.length&&this.X();return c},removeAll:function(b){if(b===p){var d=this.B(),c=d.slice(0);this.Y();d.splice(0,d.length);this.X();return c}return b?this.remove(function(c){return 0<=a.a.m(b,c)}):[]},destroy:function(b){var d=this.B(),
c="function"!=typeof b||a.F(b)?function(a){return a===b}:b;this.Y();for(var e=d.length-1;0<=e;e--)c(d[e])&&(d[e]._destroy=!0);this.X()},destroyAll:function(b){return b===p?this.destroy(function(){return!0}):b?this.destroy(function(d){return 0<=a.a.m(b,d)}):[]},indexOf:function(b){var d=this();return a.a.m(d,b)},replace:function(a,d){var c=this.indexOf(a);0<=c&&(this.Y(),this.B()[c]=d,this.X())}};a.a.o("pop push reverse shift sort splice unshift".split(" "),function(b){a.ca.fn[b]=function(){var a=
this.B();this.Y();this.Ab(a,b,arguments);a=a[b].apply(a,arguments);this.X();return a}});a.a.o(["slice"],function(b){a.ca.fn[b]=function(){var a=this();return a[b].apply(a,arguments)}});a.a.Ba&&a.a.Ja(a.ca.fn,a.r.fn);a.b("observableArray",a.ca);a.oa.trackArrayChanges=function(b){function d(){if(!c){c=!0;var f=b.notifySubscribers;b.notifySubscribers=function(a,b){b&&b!==H||++h;return f.apply(this,arguments)};var d=[].concat(b.B()||[]);e=null;g=b.V(function(c){c=[].concat(c||[]);if(b.Da("arrayChange")){var f;
if(!e||1<h)e=a.a.Qa(d,c,{sparse:!0});f=e}d=c;e=null;h=0;f&&f.length&&b.notifySubscribers(f,"arrayChange")})}}if(!b.Ab){var c=!1,e=null,g,h=0,k=b.ka,l=b.wa;b.ka=function(a){k&&k.call(b,a);"arrayChange"===a&&d()};b.wa=function(a){l&&l.call(b,a);"arrayChange"!==a||b.Da("arrayChange")||(g.p(),c=!1)};b.Ab=function(b,d,g){function l(a,b,c){return k[k.length]={status:a,value:b,index:c}}if(c&&!h){var k=[],t=b.length,w=g.length,s=0;switch(d){case "push":s=t;case "unshift":for(d=0;d<w;d++)l("added",g[d],s+
d);break;case "pop":s=t-1;case "shift":t&&l("deleted",b[s],s);break;case "splice":d=Math.min(Math.max(0,0>g[0]?t+g[0]:g[0]),t);for(var t=1===w?t:Math.min(d+(g[1]||0),t),w=d+w-2,s=Math.max(t,w),F=[],B=[],p=2;d<s;++d,++p)d<t&&B.push(l("deleted",b[d],d)),d<w&&F.push(l("added",g[p],d));a.a.Gb(B,F);break;default:return}e=k}}}};a.w=a.j=function(b,d,c){function e(a,b,c){if(I&&b===f)throw Error("A 'pure' computed must not be called recursively");A[a]=c;c.ua=E++;c.fa=b.Ca()}function g(){var a,b;for(a in A)if(A.hasOwnProperty(a)&&
(b=A[a],b.ea.uc(b.fa)))return!0}function h(){!r&&A&&a.a.A(A,function(a,b){b.p&&b.p()});A=null;E=0;F=!0;r=t=!1}function k(){var b=f.throttleEvaluation;b&&0<=b?(clearTimeout(z),z=a.a.setTimeout(function(){l(!0)},b)):f.pb?f.pb():l(!0)}function l(b){if(!w&&!F){if(v&&v()){if(!s){y();return}}else s=!1;w=!0;try{var c=A,m=E,g=I?p:!E;a.k.zb({Pa:function(a,b){F||(m&&c[b]?(e(b,a,c[b]),delete c[b],--m):A[b]||e(b,a,r?{ea:a}:a.V(k)))},w:f,Ea:g});A={};E=0;try{var l=d?B.call(d):B()}finally{a.k.end(),m&&!r&&a.a.A(c,
function(a,b){b.p&&b.p()}),t=!1}f.Za(n,l)&&(r||q(n,"beforeChange"),n=l,r?f.bc():b&&q(n));g&&q(n,"awake")}finally{w=!1}E||y()}}function f(){if(0<arguments.length){if("function"===typeof L)L.apply(d,arguments);else throw Error("Cannot write a value to a ko.computed unless you specify a 'write' option. If you wish to read the current value, don't pass any parameters.");return this}a.k.Sb(f);(t||r&&g())&&l();return n}function m(){(t&&!E||r&&g())&&l();return n}function x(){return t||0<E}function q(a,b){f.notifySubscribers(a,
b)}var n,t=!0,w=!1,s=!1,F=!1,B=b,I=!1,r=!1;B&&"object"==typeof B?(c=B,B=c.read):(c=c||{},B||(B=c.read));if("function"!=typeof B)throw Error("Pass a function that returns the value of the ko.computed");var L=c.write,C=c.disposeWhenNodeIsRemoved||c.q||null,u=c.disposeWhen||c.Ta,v=u,y=h,A={},E=0,z=null;d||(d=c.owner);a.Q.call(f);a.a.Ka(f,a.j.fn);f.B=m;f.qa=function(){return E};f.vc="function"===typeof L;f.p=function(){y()};f.aa=x;var V=f.Ga;f.Ga=function(a){V.call(f,a);f.pb=function(){f.rb(n);t=!0;f.sb(f)}};
c.pure?(r=I=!0,f.ka=function(b){if(!F&&r&&"change"==b){r=!1;if(t||g())A=null,E=0,t=!0,l();else{var c=[];a.a.A(A,function(a,b){c[b.ua]=a});a.a.o(c,function(a,b){var c=A[a],f=c.ea.V(k);f.ua=b;f.fa=c.fa;A[a]=f})}F||q(n,"awake")}},f.wa=function(b){F||"change"!=b||f.Da("change")||(a.a.A(A,function(a,b){b.p&&(A[a]={ea:b.ea,ua:b.ua,fa:b.fa},b.p())}),r=!0,q(p,"asleep"))},f.gc=f.Ca,f.Ca=function(){r&&(t||g())&&l();return f.gc()}):c.deferEvaluation&&(f.ka=function(a){"change"!=a&&"beforeChange"!=a||m()});a.D(f,
"peek",f.B);a.D(f,"dispose",f.p);a.D(f,"isActive",f.aa);a.D(f,"getDependenciesCount",f.qa);C&&(s=!0,C.nodeType&&(v=function(){return!a.a.Ua(C)||u&&u()}));a.options.deferUpdates&&a.oa.deferred(f,!0);r||c.deferEvaluation||l();C&&x()&&C.nodeType&&(y=function(){a.a.C.Tb(C,y);h()},a.a.C.ga(C,y));return f};a.xc=function(b){return a.Wa(b,a.j)};z=a.r.Fc;a.j[z]=a.r;a.j.fn={equalityComparer:J};a.j.fn[z]=a.j;a.a.Ba&&a.a.Ja(a.j.fn,a.Q.fn);a.b("dependentObservable",a.j);a.b("computed",a.j);a.b("isComputed",a.xc);
a.Rb=function(b,d){if("function"===typeof b)return a.w(b,d,{pure:!0});b=a.a.extend({},b);b.pure=!0;return a.w(b,d)};a.b("pureComputed",a.Rb);(function(){function b(a,g,h){h=h||new c;a=g(a);if("object"!=typeof a||null===a||a===p||a instanceof RegExp||a instanceof Date||a instanceof String||a instanceof Number||a instanceof Boolean)return a;var k=a instanceof Array?[]:{};h.save(a,k);d(a,function(c){var f=g(a[c]);switch(typeof f){case "boolean":case "number":case "string":case "function":k[c]=f;break;
case "object":case "undefined":var d=h.get(f);k[c]=d!==p?d:b(f,g,h)}});return k}function d(a,b){if(a instanceof Array){for(var c=0;c<a.length;c++)b(c);"function"==typeof a.toJSON&&b("toJSON")}else for(c in a)b(c)}function c(){this.keys=[];this.ob=[]}a.Zb=function(c){if(0==arguments.length)throw Error("When calling ko.toJS, pass the object you want to convert.");return b(c,function(b){for(var c=0;a.F(b)&&10>c;c++)b=b();return b})};a.toJSON=function(b,c,d){b=a.Zb(b);return a.a.lb(b,c,d)};c.prototype=
{save:function(b,c){var d=a.a.m(this.keys,b);0<=d?this.ob[d]=c:(this.keys.push(b),this.ob.push(c))},get:function(b){b=a.a.m(this.keys,b);return 0<=b?this.ob[b]:p}}})();a.b("toJS",a.Zb);a.b("toJSON",a.toJSON);(function(){a.i={s:function(b){switch(a.a.v(b)){case "option":return!0===b.__ko__hasDomDataOptionValue__?a.a.f.get(b,a.d.options.cb):7>=a.a.M?b.getAttributeNode("value")&&b.getAttributeNode("value").specified?b.value:b.text:b.value;case "select":return 0<=b.selectedIndex?a.i.s(b.options[b.selectedIndex]):
p;default:return b.value}},Z:function(b,d,c){switch(a.a.v(b)){case "option":switch(typeof d){case "string":a.a.f.set(b,a.d.options.cb,p);"__ko__hasDomDataOptionValue__"in b&&delete b.__ko__hasDomDataOptionValue__;b.value=d;break;default:a.a.f.set(b,a.d.options.cb,d),b.__ko__hasDomDataOptionValue__=!0,b.value="number"===typeof d?d:""}break;case "select":if(""===d||null===d)d=p;for(var e=-1,g=0,h=b.options.length,k;g<h;++g)if(k=a.i.s(b.options[g]),k==d||""==k&&d===p){e=g;break}if(c||0<=e||d===p&&1<
b.size)b.selectedIndex=e;break;default:if(null===d||d===p)d="";b.value=d}}}})();a.b("selectExtensions",a.i);a.b("selectExtensions.readValue",a.i.s);a.b("selectExtensions.writeValue",a.i.Z);a.h=function(){function b(b){b=a.a.kb(b);123===b.charCodeAt(0)&&(b=b.slice(1,-1));var c=[],d=b.match(e),x,k=[],n=0;if(d){d.push(",");for(var t=0,w;w=d[t];++t){var s=w.charCodeAt(0);if(44===s){if(0>=n){c.push(x&&k.length?{key:x,value:k.join("")}:{unknown:x||k.join("")});x=n=0;k=[];continue}}else if(58===s){if(!n&&
!x&&1===k.length){x=k.pop();continue}}else 47===s&&t&&1<w.length?(s=d[t-1].match(g))&&!h[s[0]]&&(b=b.substr(b.indexOf(w)+1),d=b.match(e),d.push(","),t=-1,w="/"):40===s||123===s||91===s?++n:41===s||125===s||93===s?--n:x||k.length||34!==s&&39!==s||(w=w.slice(1,-1));k.push(w)}}return c}var d=["true","false","null","undefined"],c=/^(?:[$_a-z][$\w]*|(.+)(\.\s*[$_a-z][$\w]*|\[.+\]))$/i,e=RegExp("\"(?:[^\"\\\\]|\\\\.)*\"|'(?:[^'\\\\]|\\\\.)*'|/(?:[^/\\\\]|\\\\.)*/w*|[^\\s:,/][^,\"'{}()/:[\\]]*[^\\s,\"'{}()/:[\\]]|[^\\s]",
"g"),g=/[\])"'A-Za-z0-9_$]+$/,h={"in":1,"return":1,"typeof":1},k={};return{la:[],W:k,eb:b,Ha:function(e,f){function m(b,f){var e;if(!t){var l=a.getBindingHandler(b);if(l&&l.preprocess&&!(f=l.preprocess(f,b,m)))return;if(l=k[b])e=f,0<=a.a.m(d,e)?e=!1:(l=e.match(c),e=null===l?!1:l[1]?"Object("+l[1]+")"+l[2]:e),l=e;l&&h.push("'"+b+"':function(_z){"+e+"=_z}")}n&&(f="function(){return "+f+" }");g.push("'"+b+"':"+f)}f=f||{};var g=[],h=[],n=f.valueAccessors,t=f.bindingParams,w="string"===typeof e?b(e):e;
a.a.o(w,function(a){m(a.key||a.unknown,a.value)});h.length&&m("_ko_property_writers","{"+h.join(",")+" }");return g.join(",")},Ac:function(a,b){for(var c=0;c<a.length;c++)if(a[c].key==b)return!0;return!1},ta:function(b,c,d,e,g){if(b&&a.F(b))!a.Fa(b)||g&&b.B()===e||b(e);else if((b=c.get("_ko_property_writers"))&&b[d])b[d](e)}}}();a.b("expressionRewriting",a.h);a.b("expressionRewriting.bindingRewriteValidators",a.h.la);a.b("expressionRewriting.parseObjectLiteral",a.h.eb);a.b("expressionRewriting.preProcessBindings",
a.h.Ha);a.b("expressionRewriting._twoWayBindings",a.h.W);a.b("jsonExpressionRewriting",a.h);a.b("jsonExpressionRewriting.insertPropertyAccessorsIntoJson",a.h.Ha);(function(){function b(a){return 8==a.nodeType&&h.test(g?a.text:a.nodeValue)}function d(a){return 8==a.nodeType&&k.test(g?a.text:a.nodeValue)}function c(a,c){for(var e=a,g=1,l=[];e=e.nextSibling;){if(d(e)&&(g--,0===g))return l;l.push(e);b(e)&&g++}if(!c)throw Error("Cannot find closing comment tag to match: "+a.nodeValue);return null}function e(a,
b){var d=c(a,b);return d?0<d.length?d[d.length-1].nextSibling:a.nextSibling:null}var g=u&&"\x3c!--test--\x3e"===u.createComment("test").text,h=g?/^\x3c!--\s*ko(?:\s+([\s\S]+))?\s*--\x3e$/:/^\s*ko(?:\s+([\s\S]+))?\s*$/,k=g?/^\x3c!--\s*\/ko\s*--\x3e$/:/^\s*\/ko\s*$/,l={ul:!0,ol:!0};a.e={S:{},childNodes:function(a){return b(a)?c(a):a.childNodes},na:function(c){if(b(c)){c=a.e.childNodes(c);for(var d=0,e=c.length;d<e;d++)a.removeNode(c[d])}else a.a.Va(c)},U:function(c,d){if(b(c)){a.e.na(c);for(var e=c.nextSibling,
g=0,l=d.length;g<l;g++)e.parentNode.insertBefore(d[g],e)}else a.a.U(c,d)},Qb:function(a,c){b(a)?a.parentNode.insertBefore(c,a.nextSibling):a.firstChild?a.insertBefore(c,a.firstChild):a.appendChild(c)},Jb:function(c,d,e){e?b(c)?c.parentNode.insertBefore(d,e.nextSibling):e.nextSibling?c.insertBefore(d,e.nextSibling):c.appendChild(d):a.e.Qb(c,d)},firstChild:function(a){return b(a)?!a.nextSibling||d(a.nextSibling)?null:a.nextSibling:a.firstChild},nextSibling:function(a){b(a)&&(a=e(a));return a.nextSibling&&
d(a.nextSibling)?null:a.nextSibling},tc:b,Lc:function(a){return(a=(g?a.text:a.nodeValue).match(h))?a[1]:null},Ob:function(c){if(l[a.a.v(c)]){var m=c.firstChild;if(m){do if(1===m.nodeType){var g;g=m.firstChild;var k=null;if(g){do if(k)k.push(g);else if(b(g)){var h=e(g,!0);h?g=h:k=[g]}else d(g)&&(k=[g]);while(g=g.nextSibling)}if(g=k)for(k=m.nextSibling,h=0;h<g.length;h++)k?c.insertBefore(g[h],k):c.appendChild(g[h])}while(m=m.nextSibling)}}}}})();a.b("virtualElements",a.e);a.b("virtualElements.allowedBindings",
a.e.S);a.b("virtualElements.emptyNode",a.e.na);a.b("virtualElements.insertAfter",a.e.Jb);a.b("virtualElements.prepend",a.e.Qb);a.b("virtualElements.setDomNodeChildren",a.e.U);(function(){a.L=function(){this.jc={}};a.a.extend(a.L.prototype,{nodeHasBindings:function(b){switch(b.nodeType){case 1:return null!=b.getAttribute("data-bind")||a.g.getComponentNameForNode(b);case 8:return a.e.tc(b);default:return!1}},getBindings:function(b,d){var c=this.getBindingsString(b,d),c=c?this.parseBindingsString(c,
d,b):null;return a.g.ub(c,b,d,!1)},getBindingAccessors:function(b,d){var c=this.getBindingsString(b,d),c=c?this.parseBindingsString(c,d,b,{valueAccessors:!0}):null;return a.g.ub(c,b,d,!0)},getBindingsString:function(b){switch(b.nodeType){case 1:return b.getAttribute("data-bind");case 8:return a.e.Lc(b);default:return null}},parseBindingsString:function(b,d,c,e){try{var g=this.jc,h=b+(e&&e.valueAccessors||""),k;if(!(k=g[h])){var l,f="with($context){with($data||{}){return{"+a.h.Ha(b,e)+"}}}";l=new Function("$context",
"$element",f);k=g[h]=l}return k(d,c)}catch(m){throw m.message="Unable to parse bindings.\nBindings value: "+b+"\nMessage: "+m.message,m;}}});a.L.instance=new a.L})();a.b("bindingProvider",a.L);(function(){function b(a){return function(){return a}}function d(a){return a()}function c(b){return a.a.ra(a.k.u(b),function(a,c){return function(){return b()[c]}})}function e(d,f,e){return"function"===typeof d?c(d.bind(null,f,e)):a.a.ra(d,b)}function g(a,b){return c(this.getBindings.bind(this,a,b))}function h(b,
c,d){var f,e=a.e.firstChild(c),m=a.L.instance,g=m.preprocessNode;if(g){for(;f=e;)e=a.e.nextSibling(f),g.call(m,f);e=a.e.firstChild(c)}for(;f=e;)e=a.e.nextSibling(f),k(b,f,d)}function k(b,c,d){var e=!0,m=1===c.nodeType;m&&a.e.Ob(c);if(m&&d||a.L.instance.nodeHasBindings(c))e=f(c,null,b,d).shouldBindDescendants;e&&!x[a.a.v(c)]&&h(b,c,!m)}function l(b){var c=[],d={},f=[];a.a.A(b,function I(e){if(!d[e]){var m=a.getBindingHandler(e);m&&(m.after&&(f.push(e),a.a.o(m.after,function(c){if(b[c]){if(-1!==a.a.m(f,
c))throw Error("Cannot combine the following bindings, because they have a cyclic dependency: "+f.join(", "));I(c)}}),f.length--),c.push({key:e,Ib:m}));d[e]=!0}});return c}function f(b,c,f,e){var m=a.a.f.get(b,q);if(!c){if(m)throw Error("You cannot apply bindings multiple times to the same element.");a.a.f.set(b,q,!0)}!m&&e&&a.Xb(b,f);var k;if(c&&"function"!==typeof c)k=c;else{var h=a.L.instance,x=h.getBindingAccessors||g,n=a.j(function(){(k=c?c(f,b):x.call(h,b,f))&&f.K&&f.K();return k},null,{q:b});
k&&n.aa()||(n=null)}var u;if(k){var y=n?function(a){return function(){return d(n()[a])}}:function(a){return k[a]},v=function(){return a.a.ra(n?n():k,d)};v.get=function(a){return k[a]&&d(y(a))};v.has=function(a){return a in k};e=l(k);a.a.o(e,function(c){var d=c.Ib.init,e=c.Ib.update,m=c.key;if(8===b.nodeType&&!a.e.S[m])throw Error("The binding '"+m+"' cannot be used with virtual elements");try{"function"==typeof d&&a.k.u(function(){var a=d(b,y(m),v,f.$data,f);if(a&&a.controlsDescendantBindings){if(u!==
p)throw Error("Multiple bindings ("+u+" and "+m+") are trying to control descendant bindings of the same element. You cannot use these bindings together on the same element.");u=m}}),"function"==typeof e&&a.j(function(){e(b,y(m),v,f.$data,f)},null,{q:b})}catch(g){throw g.message='Unable to process binding "'+m+": "+k[m]+'"\nMessage: '+g.message,g;}})}return{shouldBindDescendants:u===p}}function m(b){return b&&b instanceof a.N?b:new a.N(b)}a.d={};var x={script:!0,textarea:!0};a.getBindingHandler=function(b){return a.d[b]};
a.N=function(b,c,d,f){var e=this,m="function"==typeof b&&!a.F(b),g,l=a.j(function(){var g=m?b():b,k=a.a.c(g);c?(c.K&&c.K(),a.a.extend(e,c),l&&(e.K=l)):(e.$parents=[],e.$root=k,e.ko=a);e.$rawData=g;e.$data=k;d&&(e[d]=k);f&&f(e,c,k);return e.$data},null,{Ta:function(){return g&&!a.a.vb(g)},q:!0});l.aa()&&(e.K=l,l.equalityComparer=null,g=[],l.cc=function(b){g.push(b);a.a.C.ga(b,function(b){a.a.Aa(g,b);g.length||(l.p(),e.K=l=p)})})};a.N.prototype.createChildContext=function(b,c,d){return new a.N(b,this,
c,function(a,b){a.$parentContext=b;a.$parent=b.$data;a.$parents=(b.$parents||[]).slice(0);a.$parents.unshift(a.$parent);d&&d(a)})};a.N.prototype.extend=function(b){return new a.N(this.K||this.$data,this,null,function(c,d){c.$rawData=d.$rawData;a.a.extend(c,"function"==typeof b?b():b)})};var q=a.a.f.I(),n=a.a.f.I();a.Xb=function(b,c){if(2==arguments.length)a.a.f.set(b,n,c),c.K&&c.K.cc(b);else return a.a.f.get(b,n)};a.xa=function(b,c,d){1===b.nodeType&&a.e.Ob(b);return f(b,c,m(d),!0)};a.hc=function(b,
c,d){d=m(d);return a.xa(b,e(c,d,b),d)};a.Na=function(a,b){1!==b.nodeType&&8!==b.nodeType||h(m(a),b,!0)};a.wb=function(a,b){!v&&y.jQuery&&(v=y.jQuery);if(b&&1!==b.nodeType&&8!==b.nodeType)throw Error("ko.applyBindings: first parameter should be your view model; second parameter should be a DOM node");b=b||y.document.body;k(m(a),b,!0)};a.Sa=function(b){switch(b.nodeType){case 1:case 8:var c=a.Xb(b);if(c)return c;if(b.parentNode)return a.Sa(b.parentNode)}return p};a.lc=function(b){return(b=a.Sa(b))?
b.$data:p};a.b("bindingHandlers",a.d);a.b("applyBindings",a.wb);a.b("applyBindingsToDescendants",a.Na);a.b("applyBindingAccessorsToNode",a.xa);a.b("applyBindingsToNode",a.hc);a.b("contextFor",a.Sa);a.b("dataFor",a.lc)})();(function(b){function d(d,e){var f=g.hasOwnProperty(d)?g[d]:b,m;f?f.V(e):(f=g[d]=new a.Q,f.V(e),c(d,function(b,c){var e=!(!c||!c.synchronous);h[d]={definition:b,yc:e};delete g[d];m||e?f.notifySubscribers(b):a.R.Ia(function(){f.notifySubscribers(b)})}),m=!0)}function c(a,b){e("getConfig",
[a],function(c){c?e("loadComponent",[a,c],function(a){b(a,c)}):b(null,null)})}function e(c,d,f,m){m||(m=a.g.loaders.slice(0));var g=m.shift();if(g){var h=g[c];if(h){var n=!1;if(h.apply(g,d.concat(function(a){n?f(null):null!==a?f(a):e(c,d,f,m)}))!==b&&(n=!0,!g.suppressLoaderExceptions))throw Error("Component loaders must supply values by invoking the callback, not by returning values synchronously.");}else e(c,d,f,m)}else f(null)}var g={},h={};a.g={get:function(c,e){var f=h.hasOwnProperty(c)?h[c]:
b;f?f.yc?a.k.u(function(){e(f.definition)}):a.R.Ia(function(){e(f.definition)}):d(c,e)},Cb:function(a){delete h[a]},qb:e};a.g.loaders=[];a.b("components",a.g);a.b("components.get",a.g.get);a.b("components.clearCachedDefinition",a.g.Cb)})();(function(){function b(b,c,d,e){function h(){0===--w&&e(k)}var k={},w=2,s=d.template;d=d.viewModel;s?g(c,s,function(c){a.g.qb("loadTemplate",[b,c],function(a){k.template=a;h()})}):h();d?g(c,d,function(c){a.g.qb("loadViewModel",[b,c],function(a){k[l]=a;h()})}):h()}
function d(a,b,c){if("function"===typeof b)c(function(a){return new b(a)});else if("function"===typeof b[l])c(b[l]);else if("instance"in b){var e=b.instance;c(function(){return e})}else"viewModel"in b?d(a,b.viewModel,c):a("Unknown viewModel value: "+b)}function c(b){switch(a.a.v(b)){case "script":return a.a.da(b.text);case "textarea":return a.a.da(b.value);case "template":if(e(b.content))return a.a.ma(b.content.childNodes)}return a.a.ma(b.childNodes)}function e(a){return y.DocumentFragment?a instanceof
DocumentFragment:a&&11===a.nodeType}function g(a,b,c){"string"===typeof b.require?P||y.require?(P||y.require)([b.require],c):a("Uses require, but no AMD loader is present"):c(b)}function h(a){return function(b){throw Error("Component '"+a+"': "+b);}}var k={};a.g.register=function(b,c){if(!c)throw Error("Invalid configuration for "+b);if(a.g.$a(b))throw Error("Component "+b+" is already registered");k[b]=c};a.g.$a=function(a){return k.hasOwnProperty(a)};a.g.Kc=function(b){delete k[b];a.g.Cb(b)};a.g.Db=
{getConfig:function(a,b){b(k.hasOwnProperty(a)?k[a]:null)},loadComponent:function(a,c,d){var e=h(a);g(e,c,function(c){b(a,e,c,d)})},loadTemplate:function(b,d,g){b=h(b);if("string"===typeof d)g(a.a.da(d));else if(d instanceof Array)g(d);else if(e(d))g(a.a.O(d.childNodes));else if(d.element)if(d=d.element,y.HTMLElement?d instanceof HTMLElement:d&&d.tagName&&1===d.nodeType)g(c(d));else if("string"===typeof d){var l=u.getElementById(d);l?g(c(l)):b("Cannot find element with ID "+d)}else b("Unknown element type: "+
d);else b("Unknown template value: "+d)},loadViewModel:function(a,b,c){d(h(a),b,c)}};var l="createViewModel";a.b("components.register",a.g.register);a.b("components.isRegistered",a.g.$a);a.b("components.unregister",a.g.Kc);a.b("components.defaultLoader",a.g.Db);a.g.loaders.push(a.g.Db);a.g.dc=k})();(function(){function b(b,e){var g=b.getAttribute("params");if(g){var g=d.parseBindingsString(g,e,b,{valueAccessors:!0,bindingParams:!0}),g=a.a.ra(g,function(d){return a.w(d,null,{q:b})}),h=a.a.ra(g,function(d){var e=
d.B();return d.aa()?a.w({read:function(){return a.a.c(d())},write:a.Fa(e)&&function(a){d()(a)},q:b}):e});h.hasOwnProperty("$raw")||(h.$raw=g);return h}return{$raw:{}}}a.g.getComponentNameForNode=function(b){b=a.a.v(b);return a.g.$a(b)&&b};a.g.ub=function(c,d,g,h){if(1===d.nodeType){var k=a.g.getComponentNameForNode(d);if(k){c=c||{};if(c.component)throw Error('Cannot use the "component" binding on a custom element matching a component');var l={name:k,params:b(d,g)};c.component=h?function(){return l}:
l}}return c};var d=new a.L;9>a.a.M&&(a.g.register=function(a){return function(b){u.createElement(b);return a.apply(this,arguments)}}(a.g.register),u.createDocumentFragment=function(b){return function(){var d=b(),g=a.g.dc,h;for(h in g)g.hasOwnProperty(h)&&d.createElement(h);return d}}(u.createDocumentFragment))})();(function(b){function d(b,c,d){c=c.template;if(!c)throw Error("Component '"+b+"' has no template");b=a.a.ma(c);a.e.U(d,b)}function c(a,b,c,d){var e=a.createViewModel;return e?e.call(a,d,
{element:b,templateNodes:c}):d}var e=0;a.d.component={init:function(g,h,k,l,f){function m(){var a=x&&x.dispose;"function"===typeof a&&a.call(x);q=null}var x,q,n=a.a.O(a.e.childNodes(g));a.a.C.ga(g,m);a.w(function(){var l=a.a.c(h()),k,s;"string"===typeof l?k=l:(k=a.a.c(l.name),s=a.a.c(l.params));if(!k)throw Error("No component name specified");var p=q=++e;a.g.get(k,function(e){if(q===p){m();if(!e)throw Error("Unknown component '"+k+"'");d(k,e,g);var l=c(e,g,n,s);e=f.createChildContext(l,b,function(a){a.$component=
l;a.$componentTemplateNodes=n});x=l;a.Na(e,g)}})},null,{q:g});return{controlsDescendantBindings:!0}}};a.e.S.component=!0})();var Q={"class":"className","for":"htmlFor"};a.d.attr={update:function(b,d){var c=a.a.c(d())||{};a.a.A(c,function(c,d){d=a.a.c(d);var h=!1===d||null===d||d===p;h&&b.removeAttribute(c);8>=a.a.M&&c in Q?(c=Q[c],h?b.removeAttribute(c):b[c]=d):h||b.setAttribute(c,d.toString());"name"===c&&a.a.Vb(b,h?"":d.toString())})}};(function(){a.d.checked={after:["value","attr"],init:function(b,
d,c){function e(){var e=b.checked,g=x?h():e;if(!a.$.Ea()&&(!l||e)){var k=a.k.u(d);f?m!==g?(e&&(a.a.ha(k,g,!0),a.a.ha(k,m,!1)),m=g):a.a.ha(k,g,e):a.h.ta(k,c,"checked",g,!0)}}function g(){var c=a.a.c(d());b.checked=f?0<=a.a.m(c,h()):k?c:h()===c}var h=a.Rb(function(){return c.has("checkedValue")?a.a.c(c.get("checkedValue")):c.has("value")?a.a.c(c.get("value")):b.value}),k="checkbox"==b.type,l="radio"==b.type;if(k||l){var f=k&&a.a.c(d())instanceof Array,m=f?h():p,x=l||f;l&&!b.name&&a.d.uniqueName.init(b,
function(){return!0});a.w(e,null,{q:b});a.a.n(b,"click",e);a.w(g,null,{q:b})}}};a.h.W.checked=!0;a.d.checkedValue={update:function(b,d){b.value=a.a.c(d())}}})();a.d.css={update:function(b,d){var c=a.a.c(d());null!==c&&"object"==typeof c?a.a.A(c,function(c,d){d=a.a.c(d);a.a.Ma(b,c,d)}):(c=String(c||""),a.a.Ma(b,b.__ko__cssValue,!1),b.__ko__cssValue=c,a.a.Ma(b,c,!0))}};a.d.enable={update:function(b,d){var c=a.a.c(d());c&&b.disabled?b.removeAttribute("disabled"):c||b.disabled||(b.disabled=!0)}};a.d.disable=
{update:function(b,d){a.d.enable.update(b,function(){return!a.a.c(d())})}};a.d.event={init:function(b,d,c,e,g){var h=d()||{};a.a.A(h,function(h){"string"==typeof h&&a.a.n(b,h,function(b){var f,m=d()[h];if(m){try{var x=a.a.O(arguments);e=g.$data;x.unshift(e);f=m.apply(e,x)}finally{!0!==f&&(b.preventDefault?b.preventDefault():b.returnValue=!1)}!1===c.get(h+"Bubble")&&(b.cancelBubble=!0,b.stopPropagation&&b.stopPropagation())}})})}};a.d.foreach={Mb:function(b){return function(){var d=b(),c=a.a.fb(d);
if(!c||"number"==typeof c.length)return{foreach:d,templateEngine:a.P.Ya};a.a.c(d);return{foreach:c.data,as:c.as,includeDestroyed:c.includeDestroyed,afterAdd:c.afterAdd,beforeRemove:c.beforeRemove,afterRender:c.afterRender,beforeMove:c.beforeMove,afterMove:c.afterMove,templateEngine:a.P.Ya}}},init:function(b,d){return a.d.template.init(b,a.d.foreach.Mb(d))},update:function(b,d,c,e,g){return a.d.template.update(b,a.d.foreach.Mb(d),c,e,g)}};a.h.la.foreach=!1;a.e.S.foreach=!0;a.d.hasfocus={init:function(b,
d,c){function e(e){b.__ko_hasfocusUpdating=!0;var g=b.ownerDocument;if("activeElement"in g){var f;try{f=g.activeElement}catch(m){f=g.body}e=f===b}g=d();a.h.ta(g,c,"hasfocus",e,!0);b.__ko_hasfocusLastValue=e;b.__ko_hasfocusUpdating=!1}var g=e.bind(null,!0),h=e.bind(null,!1);a.a.n(b,"focus",g);a.a.n(b,"focusin",g);a.a.n(b,"blur",h);a.a.n(b,"focusout",h)},update:function(b,d){var c=!!a.a.c(d());b.__ko_hasfocusUpdating||b.__ko_hasfocusLastValue===c||(c?b.focus():b.blur(),a.k.u(a.a.sa,null,[b,c?"focusin":
"focusout"]))}};a.h.W.hasfocus=!0;a.d.hasFocus=a.d.hasfocus;a.h.W.hasFocus=!0;a.d.html={init:function(){return{controlsDescendantBindings:!0}},update:function(b,d){a.a.ib(b,d())}};K("if");K("ifnot",!1,!0);K("with",!0,!1,function(a,d){return a.createChildContext(d)});var M={};a.d.options={init:function(b){if("select"!==a.a.v(b))throw Error("options binding applies only to SELECT elements");for(;0<b.length;)b.remove(0);return{controlsDescendantBindings:!0}},update:function(b,d,c){function e(){return a.a.za(b.options,
function(a){return a.selected})}function g(a,b,c){var d=typeof b;return"function"==d?b(a):"string"==d?a[b]:c}function h(d,e){if(t&&m)a.i.Z(b,a.a.c(c.get("value")),!0);else if(n.length){var f=0<=a.a.m(n,a.i.s(e[0]));a.a.Wb(e[0],f);t&&!f&&a.k.u(a.a.sa,null,[b,"change"])}}var k=b.multiple,l=0!=b.length&&k?b.scrollTop:null,f=a.a.c(d()),m=c.get("valueAllowUnset")&&c.has("value"),x=c.get("optionsIncludeDestroyed");d={};var q,n=[];m||(k?n=a.a.Oa(e(),a.i.s):0<=b.selectedIndex&&n.push(a.i.s(b.options[b.selectedIndex])));
f&&("undefined"==typeof f.length&&(f=[f]),q=a.a.za(f,function(b){return x||b===p||null===b||!a.a.c(b._destroy)}),c.has("optionsCaption")&&(f=a.a.c(c.get("optionsCaption")),null!==f&&f!==p&&q.unshift(M)));var t=!1;d.beforeRemove=function(a){b.removeChild(a)};f=h;c.has("optionsAfterRender")&&"function"==typeof c.get("optionsAfterRender")&&(f=function(b,d){h(0,d);a.k.u(c.get("optionsAfterRender"),null,[d[0],b!==M?b:p])});a.a.hb(b,q,function(d,e,f){f.length&&(n=!m&&f[0].selected?[a.i.s(f[0])]:[],t=!0);
e=b.ownerDocument.createElement("option");d===M?(a.a.La(e,c.get("optionsCaption")),a.i.Z(e,p)):(f=g(d,c.get("optionsValue"),d),a.i.Z(e,a.a.c(f)),d=g(d,c.get("optionsText"),f),a.a.La(e,d));return[e]},d,f);a.k.u(function(){m?a.i.Z(b,a.a.c(c.get("value")),!0):(k?n.length&&e().length<n.length:n.length&&0<=b.selectedIndex?a.i.s(b.options[b.selectedIndex])!==n[0]:n.length||0<=b.selectedIndex)&&a.a.sa(b,"change")});a.a.pc(b);l&&20<Math.abs(l-b.scrollTop)&&(b.scrollTop=l)}};a.d.options.cb=a.a.f.I();a.d.selectedOptions=
{after:["options","foreach"],init:function(b,d,c){a.a.n(b,"change",function(){var e=d(),g=[];a.a.o(b.getElementsByTagName("option"),function(b){b.selected&&g.push(a.i.s(b))});a.h.ta(e,c,"selectedOptions",g)})},update:function(b,d){if("select"!=a.a.v(b))throw Error("values binding applies only to SELECT elements");var c=a.a.c(d());c&&"number"==typeof c.length&&a.a.o(b.getElementsByTagName("option"),function(b){var d=0<=a.a.m(c,a.i.s(b));a.a.Wb(b,d)})}};a.h.W.selectedOptions=!0;a.d.style={update:function(b,
d){var c=a.a.c(d()||{});a.a.A(c,function(c,d){d=a.a.c(d);if(null===d||d===p||!1===d)d="";b.style[c]=d})}};a.d.submit={init:function(b,d,c,e,g){if("function"!=typeof d())throw Error("The value for a submit binding must be a function");a.a.n(b,"submit",function(a){var c,e=d();try{c=e.call(g.$data,b)}finally{!0!==c&&(a.preventDefault?a.preventDefault():a.returnValue=!1)}})}};a.d.text={init:function(){return{controlsDescendantBindings:!0}},update:function(b,d){a.a.La(b,d())}};a.e.S.text=!0;(function(){if(y&&
y.navigator)var b=function(a){if(a)return parseFloat(a[1])},d=y.opera&&y.opera.version&&parseInt(y.opera.version()),c=y.navigator.userAgent,e=b(c.match(/^(?:(?!chrome).)*version\/([^ ]*) safari/i)),g=b(c.match(/Firefox\/([^ ]*)/));if(10>a.a.M)var h=a.a.f.I(),k=a.a.f.I(),l=function(b){var c=this.activeElement;(c=c&&a.a.f.get(c,k))&&c(b)},f=function(b,c){var d=b.ownerDocument;a.a.f.get(d,h)||(a.a.f.set(d,h,!0),a.a.n(d,"selectionchange",l));a.a.f.set(b,k,c)};a.d.textInput={init:function(b,c,l){function h(c,
d){a.a.n(b,c,d)}function k(){var d=a.a.c(c());if(null===d||d===p)d="";y!==p&&d===y?a.a.setTimeout(k,4):b.value!==d&&(u=d,b.value=d)}function w(){v||(y=b.value,v=a.a.setTimeout(s,4))}function s(){clearTimeout(v);y=v=p;var d=b.value;u!==d&&(u=d,a.h.ta(c(),l,"textInput",d))}var u=b.value,v,y;10>a.a.M?(h("propertychange",function(a){"value"===a.propertyName&&s()}),8==a.a.M&&(h("keyup",s),h("keydown",s)),8<=a.a.M&&(f(b,s),h("dragend",w))):(h("input",s),5>e&&"textarea"===a.a.v(b)?(h("keydown",w),h("paste",
w),h("cut",w)):11>d?h("keydown",w):4>g&&(h("DOMAutoComplete",s),h("dragdrop",s),h("drop",s)));h("change",s);a.w(k,null,{q:b})}};a.h.W.textInput=!0;a.d.textinput={preprocess:function(a,b,c){c("textInput",a)}}})();a.d.uniqueName={init:function(b,d){if(d()){var c="ko_unique_"+ ++a.d.uniqueName.kc;a.a.Vb(b,c)}}};a.d.uniqueName.kc=0;a.d.value={after:["options","foreach"],init:function(b,d,c){if("input"!=b.tagName.toLowerCase()||"checkbox"!=b.type&&"radio"!=b.type){var e=["change"],g=c.get("valueUpdate"),
h=!1,k=null;g&&("string"==typeof g&&(g=[g]),a.a.ja(e,g),e=a.a.yb(e));var l=function(){k=null;h=!1;var e=d(),f=a.i.s(b);a.h.ta(e,c,"value",f)};!a.a.M||"input"!=b.tagName.toLowerCase()||"text"!=b.type||"off"==b.autocomplete||b.form&&"off"==b.form.autocomplete||-1!=a.a.m(e,"propertychange")||(a.a.n(b,"propertychange",function(){h=!0}),a.a.n(b,"focus",function(){h=!1}),a.a.n(b,"blur",function(){h&&l()}));a.a.o(e,function(c){var d=l;a.a.Jc(c,"after")&&(d=function(){k=a.i.s(b);a.a.setTimeout(l,0)},c=c.substring(5));
a.a.n(b,c,d)});var f=function(){var e=a.a.c(d()),g=a.i.s(b);if(null!==k&&e===k)a.a.setTimeout(f,0);else if(e!==g)if("select"===a.a.v(b)){var l=c.get("valueAllowUnset"),g=function(){a.i.Z(b,e,l)};g();l||e===a.i.s(b)?a.a.setTimeout(g,0):a.k.u(a.a.sa,null,[b,"change"])}else a.i.Z(b,e)};a.w(f,null,{q:b})}else a.xa(b,{checkedValue:d})},update:function(){}};a.h.W.value=!0;a.d.visible={update:function(b,d){var c=a.a.c(d()),e="none"!=b.style.display;c&&!e?b.style.display="":!c&&e&&(b.style.display="none")}};
(function(b){a.d[b]={init:function(d,c,e,g,h){return a.d.event.init.call(this,d,function(){var a={};a[b]=c();return a},e,g,h)}}})("click");a.J=function(){};a.J.prototype.renderTemplateSource=function(){throw Error("Override renderTemplateSource");};a.J.prototype.createJavaScriptEvaluatorBlock=function(){throw Error("Override createJavaScriptEvaluatorBlock");};a.J.prototype.makeTemplateSource=function(b,d){if("string"==typeof b){d=d||u;var c=d.getElementById(b);if(!c)throw Error("Cannot find template with ID "+
b);return new a.t.l(c)}if(1==b.nodeType||8==b.nodeType)return new a.t.ia(b);throw Error("Unknown template type: "+b);};a.J.prototype.renderTemplate=function(a,d,c,e){a=this.makeTemplateSource(a,e);return this.renderTemplateSource(a,d,c,e)};a.J.prototype.isTemplateRewritten=function(a,d){return!1===this.allowTemplateRewriting?!0:this.makeTemplateSource(a,d).data("isRewritten")};a.J.prototype.rewriteTemplate=function(a,d,c){a=this.makeTemplateSource(a,c);d=d(a.text());a.text(d);a.data("isRewritten",
!0)};a.b("templateEngine",a.J);a.mb=function(){function b(b,c,d,k){b=a.h.eb(b);for(var l=a.h.la,f=0;f<b.length;f++){var m=b[f].key;if(l.hasOwnProperty(m)){var x=l[m];if("function"===typeof x){if(m=x(b[f].value))throw Error(m);}else if(!x)throw Error("This template engine does not support the '"+m+"' binding within its templates");}}d="ko.__tr_ambtns(function($context,$element){return(function(){return{ "+a.h.Ha(b,{valueAccessors:!0})+" } })()},'"+d.toLowerCase()+"')";return k.createJavaScriptEvaluatorBlock(d)+
c}var d=/(<([a-z]+\d*)(?:\s+(?!data-bind\s*=\s*)[a-z0-9\-]+(?:=(?:\"[^\"]*\"|\'[^\']*\'|[^>]*))?)*\s+)data-bind\s*=\s*(["'])([\s\S]*?)\3/gi,c=/\x3c!--\s*ko\b\s*([\s\S]*?)\s*--\x3e/g;return{qc:function(b,c,d){c.isTemplateRewritten(b,d)||c.rewriteTemplate(b,function(b){return a.mb.Cc(b,c)},d)},Cc:function(a,g){return a.replace(d,function(a,c,d,e,m){return b(m,c,d,g)}).replace(c,function(a,c){return b(c,"\x3c!-- ko --\x3e","#comment",g)})},ic:function(b,c){return a.H.bb(function(d,k){var l=d.nextSibling;
l&&l.nodeName.toLowerCase()===c&&a.xa(l,b,k)})}}}();a.b("__tr_ambtns",a.mb.ic);(function(){a.t={};a.t.l=function(a){this.l=a};a.t.l.prototype.text=function(){var b=a.a.v(this.l),b="script"===b?"text":"textarea"===b?"value":"innerHTML";if(0==arguments.length)return this.l[b];var d=arguments[0];"innerHTML"===b?a.a.ib(this.l,d):this.l[b]=d};var b=a.a.f.I()+"_";a.t.l.prototype.data=function(c){if(1===arguments.length)return a.a.f.get(this.l,b+c);a.a.f.set(this.l,b+c,arguments[1])};var d=a.a.f.I();a.t.ia=
function(a){this.l=a};a.t.ia.prototype=new a.t.l;a.t.ia.prototype.text=function(){if(0==arguments.length){var b=a.a.f.get(this.l,d)||{};b.nb===p&&b.Ra&&(b.nb=b.Ra.innerHTML);return b.nb}a.a.f.set(this.l,d,{nb:arguments[0]})};a.t.l.prototype.nodes=function(){if(0==arguments.length)return(a.a.f.get(this.l,d)||{}).Ra;a.a.f.set(this.l,d,{Ra:arguments[0]})};a.b("templateSources",a.t);a.b("templateSources.domElement",a.t.l);a.b("templateSources.anonymousTemplate",a.t.ia)})();(function(){function b(b,c,
d){var e;for(c=a.e.nextSibling(c);b&&(e=b)!==c;)b=a.e.nextSibling(e),d(e,b)}function d(c,d){if(c.length){var e=c[0],g=c[c.length-1],h=e.parentNode,k=a.L.instance,p=k.preprocessNode;if(p){b(e,g,function(a,b){var c=a.previousSibling,d=p.call(k,a);d&&(a===e&&(e=d[0]||b),a===g&&(g=d[d.length-1]||c))});c.length=0;if(!e)return;e===g?c.push(e):(c.push(e,g),a.a.pa(c,h))}b(e,g,function(b){1!==b.nodeType&&8!==b.nodeType||a.wb(d,b)});b(e,g,function(b){1!==b.nodeType&&8!==b.nodeType||a.H.ac(b,[d])});a.a.pa(c,
h)}}function c(a){return a.nodeType?a:0<a.length?a[0]:null}function e(b,e,g,k,q){q=q||{};var n=(b&&c(b)||g||{}).ownerDocument,p=q.templateEngine||h;a.mb.qc(g,p,n);g=p.renderTemplate(g,k,q,n);if("number"!=typeof g.length||0<g.length&&"number"!=typeof g[0].nodeType)throw Error("Template engine must return an array of DOM nodes");n=!1;switch(e){case "replaceChildren":a.e.U(b,g);n=!0;break;case "replaceNode":a.a.Ub(b,g);n=!0;break;case "ignoreTargetNode":break;default:throw Error("Unknown renderMode: "+
e);}n&&(d(g,k),q.afterRender&&a.k.u(q.afterRender,null,[g,k.$data]));return g}function g(b,c,d){return a.F(b)?b():"function"===typeof b?b(c,d):b}var h;a.jb=function(b){if(b!=p&&!(b instanceof a.J))throw Error("templateEngine must inherit from ko.templateEngine");h=b};a.gb=function(b,d,k,x,q){k=k||{};if((k.templateEngine||h)==p)throw Error("Set a template engine before calling renderTemplate");q=q||"replaceChildren";if(x){var n=c(x);return a.j(function(){var h=d&&d instanceof a.N?d:new a.N(a.a.c(d)),
p=g(b,h.$data,h),h=e(x,q,p,h,k);"replaceNode"==q&&(x=h,n=c(x))},null,{Ta:function(){return!n||!a.a.Ua(n)},q:n&&"replaceNode"==q?n.parentNode:n})}return a.H.bb(function(c){a.gb(b,d,k,c,"replaceNode")})};a.Hc=function(b,c,h,k,q){function n(a,b){d(b,w);h.afterRender&&h.afterRender(b,a);w=null}function t(a,c){w=q.createChildContext(a,h.as,function(a){a.$index=c});var d=g(b,a,w);return e(null,"ignoreTargetNode",d,w,h)}var w;return a.j(function(){var b=a.a.c(c)||[];"undefined"==typeof b.length&&(b=[b]);
b=a.a.za(b,function(b){return h.includeDestroyed||b===p||null===b||!a.a.c(b._destroy)});a.k.u(a.a.hb,null,[k,b,t,h,n])},null,{q:k})};var k=a.a.f.I();a.d.template={init:function(b,c){var d=a.a.c(c());if("string"==typeof d||d.name)a.e.na(b);else{if("nodes"in d){if(d=d.nodes||[],a.F(d))throw Error('The "nodes" option must be a plain, non-observable array.');}else d=a.e.childNodes(b);d=a.a.Nb(d);(new a.t.ia(b)).nodes(d)}return{controlsDescendantBindings:!0}},update:function(b,c,d,e,g){var h=c(),t;c=a.a.c(h);
d=!0;e=null;"string"==typeof c?c={}:(h=c.name,"if"in c&&(d=a.a.c(c["if"])),d&&"ifnot"in c&&(d=!a.a.c(c.ifnot)),t=a.a.c(c.data));"foreach"in c?e=a.Hc(h||b,d&&c.foreach||[],c,b,g):d?(g="data"in c?g.createChildContext(t,c.as):g,e=a.gb(h||b,g,c,b)):a.e.na(b);g=e;(t=a.a.f.get(b,k))&&"function"==typeof t.p&&t.p();a.a.f.set(b,k,g&&g.aa()?g:p)}};a.h.la.template=function(b){b=a.h.eb(b);return 1==b.length&&b[0].unknown||a.h.Ac(b,"name")?null:"This template engine does not support anonymous templates nested within its templates"};
a.e.S.template=!0})();a.b("setTemplateEngine",a.jb);a.b("renderTemplate",a.gb);a.a.Gb=function(a,d,c){if(a.length&&d.length){var e,g,h,k,l;for(e=g=0;(!c||e<c)&&(k=a[g]);++g){for(h=0;l=d[h];++h)if(k.value===l.value){k.moved=l.index;l.moved=k.index;d.splice(h,1);e=h=0;break}e+=h}}};a.a.Qa=function(){function b(b,c,e,g,h){var k=Math.min,l=Math.max,f=[],m,p=b.length,q,n=c.length,t=n-p||1,w=p+n+1,s,u,v;for(m=0;m<=p;m++)for(u=s,f.push(s=[]),v=k(n,m+t),q=l(0,m-1);q<=v;q++)s[q]=q?m?b[m-1]===c[q-1]?u[q-1]:
k(u[q]||w,s[q-1]||w)+1:q+1:m+1;k=[];l=[];t=[];m=p;for(q=n;m||q;)n=f[m][q]-1,q&&n===f[m][q-1]?l.push(k[k.length]={status:e,value:c[--q],index:q}):m&&n===f[m-1][q]?t.push(k[k.length]={status:g,value:b[--m],index:m}):(--q,--m,h.sparse||k.push({status:"retained",value:c[q]}));a.a.Gb(l,t,10*p);return k.reverse()}return function(a,c,e){e="boolean"===typeof e?{dontLimitMoves:e}:e||{};a=a||[];c=c||[];return a.length<=c.length?b(a,c,"added","deleted",e):b(c,a,"deleted","added",e)}}();a.b("utils.compareArrays",
a.a.Qa);(function(){function b(b,d,g,h,k){var l=[],f=a.j(function(){var f=d(g,k,a.a.pa(l,b))||[];0<l.length&&(a.a.Ub(l,f),h&&a.k.u(h,null,[g,f,k]));l.length=0;a.a.ja(l,f)},null,{q:b,Ta:function(){return!a.a.vb(l)}});return{ba:l,j:f.aa()?f:p}}var d=a.a.f.I();a.a.hb=function(c,e,g,h,k){function l(b,d){r=x[d];s!==d&&(y[b]=r);r.Xa(s++);a.a.pa(r.ba,c);t.push(r);v.push(r)}function f(b,c){if(b)for(var d=0,e=c.length;d<e;d++)c[d]&&a.a.o(c[d].ba,function(a){b(a,d,c[d].ya)})}e=e||[];h=h||{};var m=a.a.f.get(c,
d)===p,x=a.a.f.get(c,d)||[],q=a.a.Oa(x,function(a){return a.ya}),n=a.a.Qa(q,e,h.dontLimitMoves),t=[],w=0,s=0,u=[],v=[];e=[];for(var y=[],q=[],r,z=0,C,D;C=n[z];z++)switch(D=C.moved,C.status){case "deleted":D===p&&(r=x[w],r.j&&r.j.p(),u.push.apply(u,a.a.pa(r.ba,c)||[]),h.beforeRemove&&(e[z]=r,v.push(r)));w++;break;case "retained":l(z,w++);break;case "added":D!==p?l(z,D):(r={ya:C.value,Xa:a.r(s++)},t.push(r),v.push(r),m||(q[z]=r))}f(h.beforeMove,y);a.a.o(u,h.beforeRemove?a.T:a.removeNode);for(var z=
0,m=a.e.firstChild(c),G;r=v[z];z++){r.ba||a.a.extend(r,b(c,g,r.ya,k,r.Xa));for(w=0;n=r.ba[w];m=n.nextSibling,G=n,w++)n!==m&&a.e.Jb(c,n,G);!r.wc&&k&&(k(r.ya,r.ba,r.Xa),r.wc=!0)}f(h.beforeRemove,e);f(h.afterMove,y);f(h.afterAdd,q);a.a.f.set(c,d,t)}})();a.b("utils.setDomNodeChildrenFromArrayMapping",a.a.hb);a.P=function(){this.allowTemplateRewriting=!1};a.P.prototype=new a.J;a.P.prototype.renderTemplateSource=function(b,d,c,e){if(d=(9>a.a.M?0:b.nodes)?b.nodes():null)return a.a.O(d.cloneNode(!0).childNodes);
b=b.text();return a.a.da(b,e)};a.P.Ya=new a.P;a.jb(a.P.Ya);a.b("nativeTemplateEngine",a.P);(function(){a.ab=function(){var a=this.zc=function(){if(!v||!v.tmpl)return 0;try{if(0<=v.tmpl.tag.tmpl.open.toString().indexOf("__"))return 2}catch(a){}return 1}();this.renderTemplateSource=function(b,e,g,h){h=h||u;g=g||{};if(2>a)throw Error("Your version of jQuery.tmpl is too old. Please upgrade to jQuery.tmpl 1.0.0pre or later.");var k=b.data("precompiled");k||(k=b.text()||"",k=v.template(null,"{{ko_with $item.koBindingContext}}"+
k+"{{/ko_with}}"),b.data("precompiled",k));b=[e.$data];e=v.extend({koBindingContext:e},g.templateOptions);e=v.tmpl(k,b,e);e.appendTo(h.createElement("div"));v.fragments={};return e};this.createJavaScriptEvaluatorBlock=function(a){return"{{ko_code ((function() { return "+a+" })()) }}"};this.addTemplate=function(a,b){u.write("<script type='text/html' id='"+a+"'>"+b+"\x3c/script>")};0<a&&(v.tmpl.tag.ko_code={open:"__.push($1 || '');"},v.tmpl.tag.ko_with={open:"with($1) {",close:"} "})};a.ab.prototype=
new a.J;var b=new a.ab;0<b.zc&&a.jb(b);a.b("jqueryTmplTemplateEngine",a.ab)})()})})();})();
